version: '3'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=delivery
    volumes:
      - postgres_data:/var/lib/postgresql/data

  delivery-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_POSTGRES_URL: jdbc:postgresql://postgres:5432/delivery

volumes:
  postgres_data: