version: '3'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=delivery
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: