app:
  jwt:
    secret-key: ${JWT_SECRET_KEY:e41d7!3697@924k}
    issuer: ${JWT_ISSUER:delivery-api}
    expiration-hours: ${JWT_EXPIRATION_HOURS:24}

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DATABASE_POSTGRES_SCHEMA:public}

  datasource:
    url: ${DATABASE_POSTGRES_URL:jdbc:postgresql://localhost:5432/delivery}
    username: ${DATABASE_POSTGRES_USERNAME:admin}
    password: ${DATABASE_POSTGRES_PASSWORD:admin}

  flyway:
    enabled: ${FLYWAY_MIGRATION_ENABLED:true}
    schemas: ${DATABASE_POSTGRES_SCHEMA:public}
    table: delivery_schema_history

springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    tagsSorter: alpha


